name: trashsmart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_native_splash: ^2.4.7
  iconsax: ^0.0.8
  video_player: ^2.6.1
  get: ^4.7.3
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+4

  # ICON APP
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - assets/logo_tanpanama.png
    - assets/google.png
    - assets/residu.png
    - assets/b3.png
    - assets/organik.png
    - assets/anorganik.png
    - assets/kertas.png
    - assets/artikel_1.png
    - assets/artikel_2.png
    - assets/artikel_3.png
    - assets/onboard1.png
    - assets/onboard2.png
    - assets/onboard3.png
    - assets/logo_awal.png
    - assets/ornamen_1.png
    - assets/ornamen_2.png
    - assets/splash.mp4
    - assets/reminder.png
    - assets/sampahorganik.png
    - assets/kayu.png
    - assets/daun_kering.png
    - assets/botol_plastik.png
    - assets/kaleng.png
    - assets/kaca.png
    - assets/plastik.png
    - assets/baterai.png
    - assets/obat.png
    - assets/aki.png
    - assets/deterjen.png
    - assets/koran.png
    - assets/kardus.png
    - assets/kertas_hvs.png
    - assets/kantong_kertas.png
    - assets/styrofoam.png
    - assets/popok.png
    - assets/rokok.png
    - assets/masker.png
    - assets/kantong_teh.png
    - assets/icon_aplikasi.png
    - assets/user_profile.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
    - assets/icon.png
    - assets/refuse.png
    - assets/reduce.png
    - assets/reuse.png
    - assets/recycle.png
    
    #refuse
    - assets/refuse_header.png
    - assets/refuse_earth.png
    - assets/leaf.png
    - assets/tas.png
    - assets/sedotan.png
    - assets/kado.png
    - assets/hand_leaf.png
    - assets/earth.png
    - assets/money.png
    - assets/sampah.png
    
    
    #reduce
    - assets/reduce_header.png
    - assets/reduce_bln.png
    - assets/basket.png
    - assets/jar.png
    - assets/food.png
    - assets/cutlery.png

    #reuse
    - assets/reuse_header.png
    - assets/reuse_leaf.png
    - assets/reuse1.png
    - assets/reuse2.png
    - assets/reuse3.png
    - assets/reuse4.png
    - assets/reuse5.png
    - assets/reuse6.png

    #recycle
    - assets/recycle_header.png
    - assets/recycle1.png
    - assets/recycle2.png
    - assets/recycle3.png
    - assets/recycle4.png



# CONFIG ICON APP
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_aplikasi.png"
  min_sdk_android: 21