name: trashsmart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_native_splash: ^2.4.7
  iconsax: ^0.0.8
  video_player: ^2.6.1
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+4

  # ICON APP
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - assets/logo_tanpanama.png
    - assets/google.png
    - assets/residu.png
    - assets/b3.png
    - assets/organik.png
    - assets/anorganik.png
    - assets/kertas.png
    - assets/artikel_1.png
    - assets/artikel_2.png
    - assets/artikel_3.png
    - assets/onboard1.png
    - assets/onboard2.png
    - assets/onboard3.png
    - assets/logo_awal.png
    - assets/ornamen_1.png
    - assets/ornamen_2.png
    - assets/splash.mp4
    - assets/reminder.png
    - assets/icon.png

# CONFIG ICON APP
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21